baseURL = "https://cis188.org/"
languageCode = "en-us"
title = "CIS 188: DevOps"
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Schedule"
url = "/lectures/"
weight = 2

[[menu.main]]
name = "Syllabus"
url = "/syllabus/"
weight = 3

[[menu.main]]
name = "Staff"
url = "/staff/"
weight = 4

[[menu.main]]
name = "Gradescope"
url = "https://www.gradescope.com/courses/229689"
weight = 5

[[menu.main]]
name = "Piazza"
url = "https://piazza.com/upenn/spring2021/cis188/home"
weight = 6

[markup]
  [markup.highlight]
    style = "monokailight"
[params]
  colortheme = "white"
  logo = "img/logo.png"
